<?php
/**
 * 呼叫中心
 * --数据看板
 */

namespace app\apiadmin\controller\outbound;

use app\common\controller\Backend;
use app\common\lib\outbound\xiaojianke\Call;

class OutboundCall extends Backend
{
    /**
     * 外呼配置信息
     * @var array|mixed
     */
    private $account_config = [];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $apiConfig = config('global_config.account_outbound');

        if (empty($apiConfig['app_secret']) || empty($apiConfig['app_id'])) {
            $this->ajaxReturn(4040, '请先完成外呼配置');
        }

        $this->account_config = $apiConfig;
    }


    public function call()
    {
        $param = [
            'contact_mobile' => input('post.mobile/s', '', 'trim')
        ];

        if (!fieldRegex($param['contact_mobile'], 'mobile')) {
            $this->ajaxReturn(500, '请输入正确的外呼号码');
        }

        $seatsId = model('outbound.OutbountSeats')
            ->where('admin_id', $this->admininfo->id)
            ->value('seat_id');

        if (empty($seatsId)) {
            $this->ajaxReturn(500, '请先绑定坐席');
        }
        $param['seat_id'] = $seatsId;

        try {
            $callSeat = new Call($param, $this->account_config);
            $result = $callSeat->dialing();

            if (false === $result) {
                $this->ajaxReturn($callSeat->getErrorCode(), $callSeat->getError());
            }

            $this->ajaxReturn(200, 'SUCCESS', $result['data']);
        } catch (\Exception $e) {
            $this->ajaxReturn(500, $e->getMessage());
        }
    }


}